const PROJECT_ID = "turn2026-c6b9d";
const CLIENT_EMAIL = "firebase-adminsdk-fbsvc@turn2026-c6b9d.iam.gserviceaccount.com";
const PRIVATE_KEY = "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDV8x6WveTohVBu\nP3PNUBXtKDGTZZXLdlzrxe86pjFUIhhBpi9nMYbTFfScYHw/tgzYRQT8iUP6SD1p\ngnEdG/dNNpxblzmsWrA1BeO61XRQPy9RBgcc2BwfQ3r5Com3GAyXzeKV8saOU1Tc\nxUx5+d0lROEEXDhl6FyMaa+aFCnFkhUUsgVT0YyjbtGlFVG23BY1aTIj+95YQDzw\n3oFNIerWWJSa0zVjgO+hMaJNk+3XgepRdSaQfLUeueLOg1UgKzmOTqEEtZdByufD\nBX7+pSLII0xp1Mj31yCS89NK7ktfe+xAypTyJma4vDlAvvpCJ/PfqSnHAAkjpnWE\nm1+v3fJNAgMBAAECggEAHEi/yn3gPT0inPCWhpYH0Ap4Q1wyqWtEbYcFUWOXMeAw\nBL3LloDdqhpE9EdtJZ8To6O8PQaIjhXuyHwOKCMCVprZoOIlJbv3f4r/yDtf3Rv9\nTWDWn+GSFi/9md7ixenQAGGfiuNFjJtHpMgQjC+UJNEuTj1C13YYhheSt3Pi8dNY\nOlrUi3+G2Hl2aEEHua4Mn8Vvkwv7FDBXAYrnlZ9Xvs6dJG7REdUTMTQ9OrheNYA7\nvFSM9dajxKgmRkiDzUWYmyOs0WyUDdJEnaLrCe2HyR6VIVN33MciiaOyTbvOJwqy\nSzTsZlSlMOJpJUeYD40gfm7KUkRfavx5/gaYsppzoQKBgQDyyoCJkAmyH3sPPjyn\nkpdi74as1O9ttDkiutgvc4RBK2spsj5pkQMRPlYjYHEfWEfv7o+jW+8Kv7oCLnzv\nKLdRz+qKcucYorYdDUocGpPXfrGcWJv6xGUUFHGorzRI04L3yKIkviUHtlxoEEY8\nFhkGBmmnY4XOwYBylfFAOivpkwKBgQDhlu0zt9diq6etjK8P8QogyBHQ766nANMB\nGV2/R1P9Zql1sSa3eW5bAm5VlyobYjKdHhnzald8pvrTq6S2Kju1m/1DkUrnvWMy\nuFiPL+3JUUr5HIzr+kVkpCUnBTVJI/CkZfrUGI3p1mtW/WRBn/fDMelxz4q5kzNW\niXnwYnSgnwKBgGe7z7l2uj3Jp4l2vPGX92iFEJSNkhLcOsE09aMohuxVQb8Z8gKm\nu5nFeYY58XtD+9BurB5O7E46Zp4CAM0qJ1EkNYCb4VMsSgUVpYFmdZ5P+lDjpxk4\nijtPFNTOrtciz8VQir6KI0YtS0QHGAsaIezqFoA3THdvQ5Mxr1cSw6pTAoGAd9z/\nsAkwskbO01H6+pdycDSd8sxHmoi/lMfrneTCZdQUmmpEThyBXG4QPf4R63bjucPy\nufl4/syiXbHH1Nrf2wFFMo+So0tn191HgN1QlTVShsZ6wi+6i10EOJV12KT2CgP9\noJBjZyn84r3EdXIP7XEpvsUtyqjCEGr/lZBas7UCgYAqKpYmiJCNq0A5sVluWrCp\ng5gR8GPp+Db4/LuGHTRFtqDIWkQKSGfmMPlR7zBp6C5yV5IJ+0NTP2zFUCwopolz\ndgaXQhAsaGdkrk5pxnNkdYM0xL6ywokA9rZLkJOZhKRuc058+EvSDYujVGtzYVVB\nFCJFhCc/SJxfNVxSYt42xg==\n-----END PRIVATE KEY-----\n";
export const CORS = {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"GET,POST,PUT,DELETE,OPTIONS","Access-Control-Allow-Headers":"Content-Type","Cache-Control":"no-store"};
function b64url(input){let bytes=input instanceof Uint8Array?input:new TextEncoder().encode(input);let bin="";bytes.forEach(b=>bin+=String.fromCharCode(b));return btoa(bin).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"");}
async function importKey(){const pem=PRIVATE_KEY.replace(/-----BEGIN PRIVATE KEY-----|-----END PRIVATE KEY-----|\n/g,"");const raw=Uint8Array.from(atob(pem),c=>c.charCodeAt(0));return crypto.subtle.importKey("pkcs8",raw.buffer,{name:"RSASSA-PKCS1-v1_5",hash:"SHA-256"},false,["sign"]);}
let tokenCache={token:null,exp:0};
async function getToken(){const now=Math.floor(Date.now()/1000);if(tokenCache.token&&tokenCache.exp-60>now)return tokenCache.token;const header=b64url(JSON.stringify({alg:"RS256",typ:"JWT"}));const payload=b64url(JSON.stringify({iss:CLIENT_EMAIL,scope:"https://www.googleapis.com/auth/datastore",aud:"https://oauth2.googleapis.com/token",iat:now,exp:now+3600}));const key=await importKey();const sig=await crypto.subtle.sign("RSASSA-PKCS1-v1_5",key,new TextEncoder().encode(`${header}.${payload}`));const jwt=`${header}.${payload}.${b64url(new Uint8Array(sig))}`;const r=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({grant_type:"urn:ietf:params:oauth:grant-type:jwt-bearer",assertion:jwt})});const d=await r.json();if(!r.ok)throw new Error(d.error_description||d.error||"token error");tokenCache={token:d.access_token,exp:now+Number(d.expires_in||3600)};return d.access_token;}
export function val(v){if(v===null||v===undefined)return{nullValue:null};if(Array.isArray(v))return{arrayValue:{values:v.map(val)}};if(typeof v==="object"){if(v.seconds)return{timestampValue:new Date(Number(v.seconds)*1000).toISOString()};return{mapValue:{fields:Object.fromEntries(Object.entries(v).map(([k,x])=>[k,val(x)]))}};}if(typeof v==="number")return Number.isInteger(v)?{integerValue:String(v)}:{doubleValue:v};if(typeof v==="boolean")return{booleanValue:v};return{stringValue:String(v)};}
export function unval(f){if(!f)return null;if("stringValue"in f)return f.stringValue;if("integerValue"in f)return Number(f.integerValue);if("doubleValue"in f)return Number(f.doubleValue);if("booleanValue"in f)return f.booleanValue;if("timestampValue"in f)return{seconds:Math.floor(new Date(f.timestampValue).getTime()/1000)};if("arrayValue"in f)return(f.arrayValue.values||[]).map(unval);if("mapValue"in f)return Object.fromEntries(Object.entries(f.mapValue.fields||{}).map(([k,v])=>[k,unval(v)]));return null;}
export function docToObj(doc){const fields=doc.fields||{};const obj=Object.fromEntries(Object.entries(fields).map(([k,v])=>[k,unval(v)]));obj.id=doc.name.split("/").pop();return obj;}
export async function fs(path,options={}){const token=await getToken();const r=await fetch(`https://firestore.googleapis.com/v1/projects/${PROJECT_ID}/databases/(default)/documents/${path}`,{...options,headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json",...(options.headers||{})}});const text=await r.text();const data=text?JSON.parse(text):{};if(!r.ok)throw new Error(data.error?.message||text||"firestore error");return data;}
export function json(data,status=200){return Response.json(data,{status,headers:CORS});}
export function onRequestOptions(){return new Response(null,{status:204,headers:CORS});}
